runtime: nodejs18  # Or the appropriate Node.js version you are using
instance_class: F2  # Optional, specifies the instance class (choose depending on your app's resource needs)

handlers:
  - url: /.*
    secure: always  # Ensure all connections use HTTPS/WSS
    script: auto
